* XLSX

[[https://travis-ci.org/tealeg/xlsx][https://img.shields.io/travis/tealeg/xlsx/master.svg?style=flat-square]]
[[https://codecov.io/gh/tealeg/xlsx][https://codecov.io/gh/tealeg/xlsx/branch/master/graph/badge.svg]]
[[https://godoc.org/github.com/tealeg/xlsx][https://godoc.org/github.com/tealeg/xlsx?status.svg]]
[[https://github.com/tealeg/xlsx#license][https://img.shields.io/badge/license-bsd-orange.svg]]

** Introduction
xlsx is a library to simplify reading and writing the XML format used
by recent version of Microsoft Excel in Go programs.

The support for writing XLSX files is currently extremely minimal.  It
will expand slowly, but in the meantime patches are welcome!

** Full API docs
The full API docs can be viewed using go's built in documentation
tool, or online at godoc.org for the [[http://godoc.org/github.com/tealeg/xlsx][xlsx]] and [[http://godoc.org/github.com/tealeg/xlsx/stream][stream]] packages.

** Basic Usage
*** Reading XLSX files
Here is a minimal example usage that will dump all cell data in a
given XLSX file.  A more complete example of this kind of
functionality is contained in [[https://github.com/tealeg/xlsx2csv][the XLSX2CSV program]]:

#+BEGIN_SRC go

package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    excelFileName := "/home/tealeg/foo.xlsx"
    xlFile, err := xlsx.OpenFile(excelFileName)
    if err != nil {
        fmt.Printf(err.Error())
        return
    }
    for _, sheet := range xlFile.Sheets {
        for _, row := range sheet.Rows {
            for _, cell := range row.Cells {
                text := cell.String()
                fmt.Printf("%s\n", text)
            }
        }
    }
}

#+END_SRC

Some additional information is available from the cell (for example,
style information).  For more details see the godoc output for this
package.

*** Writing XLSX files
The following constitutes the bare minimum required to write an XLSX document.

#+BEGIN_SRC go

package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    var file *xlsx.File
    var sheet *xlsx.Sheet
    var row *xlsx.Row
    var cell *xlsx.Cell
    var err error

    file = xlsx.NewFile()
    sheet, err = file.AddSheet("Sheet1")
    if err != nil {
        fmt.Printf(err.Error())
        return
    }
    row = sheet.AddRow()
    cell = row.AddCell()
    cell.Value = "I am a cell!"
    err = file.Save("MyXLSXFile.xlsx")
    if err != nil {
        fmt.Printf(err.Error())
        return
    }
}

#+END_SRC

*** Stream Writing XLSX files
This library also supports stream writing to XLSX files.  This feature is new, and is not yet feature complete. Also the
API of these classes are still subject to breaking change as new features are added.
To use:
1. Create a StreamFileBuilder with NewStreamFileBuilder() or NewStreamFileBuilderForPath().
2. The most commonly used strings in the spreadsheet data may be passed into AddSharedStrings() as an optimization. (Optional)
3. Add the sheets and their first row of data by calling AddSheet().
4. Call Build() to get a StreamFile. Once built, all functions on the builder will return an error.
5. Write to the StreamFile with WriteRow(). Writes begin on the first sheet. New rows are always written and flushed to the io.
All rows written to the same sheet must have the same number of cells as the header provided when the sheet was created or an error will be returned.
6. Call NextSheet() to proceed to the next sheet. Once NextSheet() is called, the previous sheet can not be edited.
7. Call Close() to finish.

#+BEGIN_SRC go

package main

import (
    "fmt"
    "io"
    "os"
    "github.com/tealeg/xlsx"
)

func main() {
    file, err := os.Create("stream.xlsx")
    if err != nil {
        fmt.Printf(err.Error())
        return
    }
    err = streamWriteFile(file)
    if err != nil {
        fmt.Printf(err.Error())
        return
    }
}

func streamWriteFile(writer io.Writer) error {
    var streamFileBuilder *xlsx.StreamFileBuilder
    var streamFile *xlsx.StreamFile
    var err error

    streamFileBuilder = xlsx.NewStreamFileBuilder(writer)
    err = streamFileBuilder.AddSheet("Sheet1", []string{"Header 1", "Header 2"})
    if err != nil {
        return err
    }
    streamFile, err = streamFileBuilder.Build()
    if err != nil {
        return err
    }
    err = streamFile.WriteRow([]string{"I am cell A2", "I am cell B2"})
    if err != nil {
        return err
    }
    err = streamFile.Close()
    if err != nil {
        return err
    }
}

#+END_SRC

** Contributing

We're extremely happy to review pull requests.  Please be patient, maintaining XLSX doesn't pay anyone's salary (to my knowledge).

If you'd like to propose a change please ensure the following:

- All existing tests are passing.
- There are tests in the test suite that cover the changes you're making.
- You have added documentation strings (in English) to (at least) the public functions you've added or modified.
- Your use of, or creation of, XML is compliant with
[[http://www.ecma-international.org/publications/standards/Ecma-376.htm][part 1 of the 4th edition of the ECMA-376 Standard for Office Open XML]].

In `TestXlsxStreamWrite` in [[https://github.com/tealeg/xlsx/stream/stream_test.go][stream/stream_test.go]] there is a
flag called `TestsShouldMakeRealFiles`. When set to true the test will make XLSX files in the file system instead of in
memory. This is useful to ensure files open in Excel, Numbers, Google Docs, etc.

If the generated XLSX files are not opening correctly you can use [[https://www.microsoft.com/en-us/download/details.aspx?id=30425][Open XML SDK 2.5]]
to diagnose issues in generated XLSX files. This tool only works in Windows. If you would like to use it on other systems
you can install [[https://www.virtualbox.org/][VirtualBox]] and download a [[https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/][Windows VM]]
from Microsoft. These VMs are released by Microsoft for compatiblity testing. The VMs expire after 90 days, so once you
get the VM set up how you want, take a snapshot with VirtualBox so that you can roll back when the VM expires (The
Microsoft support docs themselves will tell you to do this). The Windows VM comes in a zip that cannot be opend by macOS
Archive Utility, you will need [[https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12][The Unarchiver]] from
the Mac App Store.

** License
This code is under a BSD style license:

#+BEGIN_EXAMPLE

  Copyright 2011-2015 Geoffrey Teale. All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.  Redistributions
  in binary form must reproduce the above copyright notice, this list of
  conditions and the following disclaimer in the documentation and/or
  other materials provided with the distribution.  THIS SOFTWARE IS
  PROVIDED BY Geoffrey Teale ``AS IS'' AND ANY EXPRESS OR IMPLIED
  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL GEOFFREY TEALE OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
  IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#+END_EXAMPLE

Eat a peach - Geoff
